---
title: "ACTEX Study Manual for Exam PA: Section 1.5 (End-of-Chapter Practice Problems)"
author: "Ambrose Lo"
---

```{r}
# Problem 1.5.2
# Part (b)
LL <- function(observed, predicted){
  predicted_pos <- ifelse(predicted <= 0, 0.000001, predicted)
  return(sum(observed*log(predicted_pos) - predicted))
}

# Part (c)
observed <- c(2, 3, 6, 7, 8, 9, 10, 12, 15)
predicted <- c(2.516332, 2.516332, 7.451633, 7.451633, 7.451633, 7.451633,
               12.386934, 12.386934, 12.386934)
LL(observed, predicted)
```


```{r}
# Problem 1.5.3
x <- 1:8
name <- c("Embryo Luo", "", "Peter Smith", NA,
          "Angela Peterson", "Emily Johnston", "Barbara Scott", "Benjamin Eng")
gender <- c("M", "F", "M", "O", "F", "F", "F", "M")
age <- c(-1, 25, 22, 50, 30, 42, 29, 36)
exams <- c(10, 3, 0, 4, 6, 7, 5, 9)
Q1 <- c(10, NA, 4, 7, 8, 9, 8, 7)
Q2 <- c(9, 9, 5, 7, 8, 10, 9, 8)
Q3 <- c(9, 7, 5, 8, 10, 10, 7, 8)
actuary <- data.frame(x, name, gender, age, exams, Q1, Q2, Q3)
actuary.n <- na.omit(actuary)
actuary.n$S <- (actuary.n$Q1 + actuary.n$Q2 + actuary.n$Q3) / 3

actuary.n$classify <- ifelse(actuary.n$S >= 9, "Excellent",
                             ifelse(actuary.n$S > 7, "Good", "Unsatisfactory"))
actuary.n
```


```{r}
# Problem 1.5.4
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))
```


```{r}
# Problem 1.5.5
# (a)
# Solution based on recursive definitions
Fib <- function(n) {
  if (n == 1 | n == 2) {
    x <- 1
  } else {
    x <- Fib(n - 1) + Fib(n - 2)
  }
  return(x)
}

# Solution using a for loop
Fib <- function(n) {
  if (n == 1 | n == 2) {
    return(1)  # the function will stop at this point if n is 1 or 2
  }
  x <- rep(NA, n)
  x[1] <- x[2] <- 1
  for (i in 3:n) {
    x[i] <- x[i - 1] + x[i - 2]
  }
  return(x[n])
}

# (b)
Fib(2)
Fib(3)
Fib(5)
Fib(10)
Fib(50)
```


```{r}
# Problem 1.5.6
# Old code
n <- 100
n_sim <- 10000
beta0 <- 2  # true intercept
beta1 <- 4  # true slope
sigma <- 1  # true random error standard deviation 

count <- rep(NA, n_sim)

set.seed(0)
x <- runif(n)  # predictor values are uniform on (0,1)
x0 <- 0.8      # predictor value of interest
y0 <- rnorm(1, mean = beta0 + beta1 * x0, sd = sigma)  # target of prediction

for (i in 1:n_sim) {
  y <- rnorm(n, mean = beta0 + beta1 * x, sd = sigma)
  m <- lm(y ~ x)
  # lower bound of 95% prediction interval
  l <- predict(m, newdata = data.frame(x = x0), interval = "prediction")[, 2]
  # upper bound of 95% prediction interval
  u <- predict(m, newdata = data.frame(x = x0), interval = "prediction")[, 3]
  count[i] <- (l <= y0 <= u)
}

mean(count)
```


```{r}
# Problem 1.5.6
# New code
n <- 100
n_sim <- 10000
beta0 <- 2  # true intercept
beta1 <- 4  # true slope
sigma <- 1  # true random error standard deviation

count <- rep(NA, n_sim)

set.seed(0)
x <- runif(n)  # predictor values are uniform on (0,1)
x0 <- 0.8      # predictor value of interest

for (i in 1:n_sim) {
  y <- rnorm(n, mean = beta0 + beta1 * x, sd = sigma)
  m <- lm(y ~ x)
  y0 <- rnorm(1, mean = beta0 + beta1 * x0, sd = sigma)  # target of prediction
  # lower bound of 95% prediction interval
  l <- predict(m, newdata = data.frame(x = x0), interval = "prediction")[, 2]
  # upper bound of 95% prediction interval
  u <- predict(m, newdata = data.frame(x = x0), interval = "prediction")[, 3]
  count[i] <- (l <= y0 & y0 <= u)
}

mean(count)
```