---
title: "ACTEX Study Manual for Exam PA: Section 5.2 (Mini-Case Study: A Toy Decision Tree)"
author: "Ambrose Lo"
---


```{r}
# CHUNK 1
# Clean the working memory
rm(list = ls())

X1 <- c(1, 2, 3, 4, 2, 1)
X2 <- c(0, 1, 2, 1, 2, 1)
Y <- c(1.2, 2.1, 1.5, 3.0, 2.0, 1.6)
dat <- data.frame(X1, X2, Y)
```


```{r}
# CHUNK 2
# Uncomment the next two lines the first time you use these two packages
# install.packages("rpart")
# install.packages("rpart.plot")
library(rpart)
library(rpart.plot)

dt <- rpart(Y ~ .,
            data = dat,
            control = rpart.control(minsplit = 1,
                                    minbucket = 1,
                                    cp = 0,
                                    xval = 6))
rpart.plot(dt)
```


```{r}
# CHUNK 3
ols <- lm(Y ~ X1 * X2, data = dat)
summary(ols)
```


```{r}
# CHUNK 4
dt
```


```{r}
# CHUNK 5
dt$cptable
```


```{r}
# CHUNK 6
dt.new <- rpart(Y ~ .,
                data = dat,
                control = rpart.control(minsplit = 1,
                                        minbucket = 1,
                                        maxdepth = 3,
                                        cp = 0,
                                        xval = 6))
rpart.plot(dt.new)
dt.new$cptable
```


```{r}
# CHUNK 7
cp.min <- dt$cptable[which.min(dt$cptable[, "xerror"]), "CP"]
cp.min
dt.pruned <- prune(dt, cp = cp.min)
rpart.plot(dt.pruned)
```